FROM node:14-alpine as builder

WORKDIR /app/

COPY package.json yarn.lock ./

RUN yarn install

COPY . ./

RUN yarn build --production

# nginx state for serving content
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets from builder stage
COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]